spring:
  jpa:
    # 전송 쿼리 확인
    show-sql : true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization : true

  # 일래스틱 빈스토크에서 값을 덮어쓰므로 주석처리
#  datasource: # db정보 추가
#    url: jdbc:h2:mem:testdb

  h2: #h2 콘솔 활성화 -> db 추가되는 데이터 확인을 위함
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - email
              - profile


  #토큰 제공자 추가
  # 띄어쓰기 중요, 아래 :뒤 안하면 에러 발생
jwt:
  issuer: sunuk.kim0320@gmail.com
  secret_key: testKey